### ISSUE TITLE
When running demos: Unable to load '@webpack-cli/serve' command - TypeError: options.forEach is not a function

### ISSUE THREAD

**Issue by paulseawa** [nacular/doodle#27]
I cloned the demos from github but I am unable to run them. 

When running any of the jsBrowser*Run targets, I get the following error:

```[webpack-cli] Unable to load '@webpack-cli/serve' command
[webpack-cli] TypeError: options.forEach is not a function
[webpack-cli] TypeError: options.forEach is not a function
    at WebpackCLI.makeCommand (C:\Users\pauls\projects\kforum\build\js\node_modules\webpack-cli\lib\webpack-cli.js:173:21)
    at ServeCommand.apply (C:\Users\pauls\projects\kforum\build\js\node_modules\@webpack-cli\serve\lib\index.js:41:19)
    at loadCommandByName (C:\Users\pauls\projects\kforum\build\js\node_modules\webpack-cli\lib\webpack-cli.js:907:35)
    at async Command.<anonymous> (C:\Users\pauls\projects\kforum\build\js\node_modules\webpack-cli\lib\webpack-cli.js:1462:17)
    at async Promise.all (index 0)
    at async WebpackCLI.run (C:\Users\pauls\projects\kforum\build\js\node_modules\webpack-cli\lib\webpack-cli.js:1500:9)
    at async runCLI (C:\Users\pauls\projects\kforum\build\js\node_modules\webpack-cli\lib\bootstrap.js:11:9)```

I found [this stackoverflow](https://github.com/webpack/webpack/issues/14443) which seems to talk about the issue, but I don't know how to adjust the version of webpack that is being used by kotlin.

Can you guys repro and do you have any suggestions?

**Comment by paulseawa** [comment]
[](url)

**Comment by paulseawa** [comment]
Oops, didn't mean to close.

**Comment by pusolito** [comment]
I haven't seen this myself. But it sounds related to this issue: https://youtrack.jetbrains.com/issue/KT-49124. Let me know if any of the suggested work-arounds unblock you.

**Comment by paulseawa** [comment]
Yes, that did the trick, thanks!

I applied the first suggestion in the root build.gradle.kts file:

```
rootProject.plugins.withType<org.jetbrains.kotlin.gradle.targets.js.yarn.YarnPlugin> {
    rootProject.the<org.jetbrains.kotlin.gradle.targets.js.yarn.YarnRootExtension>().apply {
        resolution("@webpack-cli/serve", "1.5.2")
    }
}
```
