### ISSUE TITLE
I cannot get the doodle-tutorials working

### ISSUE THREAD

**Issue by mminke** [nacular/doodle#28]
I am trying to run the CalculatorRunner jvm main instance, but without luck. I keep on getting:

`
Exception in thread "main" java.lang.ExceptionInInitializerError
	at org.jetbrains.skiko.SkiaWindow$1.invoke(SkiaWindow.kt:7)
	at org.jetbrains.skiko.SkiaWindow$1.invoke(SkiaWindow.kt:7)
	at org.jetbrains.skiko.SkiaWindow.<init>(SkiaWindow.kt:9)
	at org.jetbrains.skiko.SkiaWindow.<init>(SkiaWindow.kt:5)
	at io.nacular.doodle.application.ApplicationHolderImpl.<init>(Application.kt:86)
	at io.nacular.doodle.application.ApplicationHolderImpl.<init>(Application.kt:72)
	at io.nacular.doodle.application.ApplicationHolderImpl$Companion.invoke(Application.kt:168)
	at io.nacular.doodle.application.ApplicationKt.createApplication(Application.kt:70)
	at io.nacular.doodle.examples.MainKt.main(main.kt:21)
	at io.nacular.doodle.examples.MainKt.main(main.kt)
Caused by: org.jetbrains.skiko.LibraryLoadException: Cannot find libskiko-linux-x64.so.sha256, proper native dependency missing.
	at org.jetbrains.skiko.Library.load(Library.kt:72)
	at org.jetbrains.skiko.SkiaLayer.<clinit>(SkiaLayer.kt:25)
	... 10 more
`

I saw another issue which was resolved by adding the jetbrains repo, but this one is defined in the tutorials so that is not the problem.

My setup is Ubuntu 21.10 with IntelliJ IDEA 2021.3.1 (Community Edition).
I just cloned the doodle-tutorials repo and tried to run the example app. I also tried to look for this error but could not get any good working solution for my situation. 

Really curious what I am doing wrong here.

**Comment by pusolito** [comment]
Thanks for catching this. This shows there is a gap in how the Desktop library dependencies work now. The published lib depends on the MacOS Skiko lib. Which means things won't work on Linux or Windows yet 😬. This will likely require different kind for the platforms.

In the meantime, you can add an explicit dependency on Skiko for Linux like "org.jetbrains.skiko-jvm-runtime-linux-x64:0.4.16" in the PhotosRunner build.gradle.kts (for example).

**Comment by mminke** [comment]
thanks for the quick response and fix. I can confirm that your commit fixed the issue.
I was quite on the right track, but my mistake was to include the latest skiko-jvm runtime library which did not work.
I can now run the examples.

**Comment by pusolito** [comment]
Glad to hear it. Desktop support is still pretty early, so the edges are rough. Please share any feedback or other issues you find.
